### PR TITLE
Refactor docker

### PR DESCRIPTION
**Pull request by nigeon**
Modified mongo image. 
Added .env.example file Tested endpoints and tests.

### CODE REVIEW

**Review by p4u — CHANGES_REQUESTED** [review]
The .env.example file is placed in a wrong path, it should go to dockerfiles.

However, instead of creating a new env it would be better to expand the current existing .env with the new options (commented) and its proper documentation comments. 

Finally, the docker-compose-oauth requires the line ` env_file: ".env"` in order to consider the env file.

Also, if we are finally using an .env file, it is better to not use flags in the docker compose file (environment section) but instead have everyting into the compose YML.

**Comment by nigeon** [comment]
hmm not sure why this is now failing. Will investigate

**Comment by altergui** [comment]
i created a separate PR #48, and cherry-picked that fix into this branch as well to make the tests pass

**Comment by nigeon** [comment]
This looks good to me to be reviewed and merged @p4u

**Review by altergui — CHANGES_REQUESTED** [review]
i believe you commited `blind-csp` binary in the repo by mistake?

**Comment by nigeon** [comment]
Probably. Shouln't the binary be in the .gitignore?

**Comment by altergui** [comment]
definitely should be in .gitignore (which now i see it doesn't even exist)
and ..... :rofl:  blind-csp is *already* committed since a month ago :facepalm: 
did PR #49

**Review by altergui — APPROVED** [review]
LGTM, love the modern container, great work

**Comment by altergui** [comment]
i believe the ideal would be to approve and merge #49 first, then rebase & squash #47 into a single commit

**Comment by nigeon** [comment]
@p4u plz

**Comment by p4u** [comment]
I merged #49 
Please fix the conflict so we can squash and merge.

**Comment by nigeon** [comment]
Fixed, squashed and ready

**Pull request merged**
